[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Static portfolio website for Adam Trabold"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask>=3.1.0",
]
